/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 969abb8f39bf51dca7a9f1b1e0bfb9d7)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	SENTRY_DSN: string;
	MyAgent: DurableObjectNamespace<import("./worker/index").MyAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "MyAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_DSN">> {}
}
