/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3a6a88ea485183d9619744b640292698)
interface __BaseEnv_Env {
	MyAgent: DurableObjectNamespace<import("./worker/index").MyAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "MyAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
